### ISSUE TITLE
Is the driver available in ubuntu 22.04 & ROS2 Humble?

### ISSUE THREAD

**Issue by 09krish** [ai4ce/insta360_ros_driver#6]
Hello, 

I have the Insta 360 X2 camera, but I am using ubuntu 22.04 and ROS2 Humble, Is the Humble version of the driver availaible? or should i have to use the ROS bridge to make this work? or I am open to any other Ideas?

Thank You,
Krish

**Comment by Abanesjo** [comment]
Yes, we have plans to create a ROS2 Branch, since Noetic is nearing its EOL. This will be released soon, before the end of this year. 

In the meantime, you can always set the camera to USB mode. You can then use the [usb_cam](https://index.ros.org/p/usb_cam/) package to extract images, but they will not be fisheye.

**Comment by Abanesjo** [comment]
The ROS2 humble branch is now available. Please refer to the "humble" branch. It is still in development, as of this moment, but camera bringup is working.

**Comment by Eecornwell** [comment]
@Abanesjo thank you for your great work, I am able to get insta360 One X2 bringup launch working on Humble and ubuntu 22.04. What is a quick way I could pull images off since looks like that branch is still in dev and bag_record doesn't seem to work yet.
```
~/ws_insta$ ros2 launch insta360_ros_driver bag_record.launch.py
[INFO] [launch]: All log files can be found below /home/orion/.ros/log/2025-03-02-19-00-30-129299-orion-DNB20-series-28738
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'directory_verification' not found on the libexec directory '/home/orion/ws_insta/install/insta360_ros_driver/lib/insta360_ros_driver'
```

**Comment by Abanesjo** [comment]
Since ROS2 makes changes to the filesystem with the _install_ folder, we have not yet been able to port the directory verifying tools in the ROS1 version that arrange the bag files for you.

However, if you just want to grab and save the topics, you can use the default ros commands. For ROS2 humble, you can save the topics via the following in another terminal once you've brought up the insta360 node.
```
ros2 bag record -a
```
For more information:
[Recording Data in ROS2 Humble](https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.html)

**Comment by Eecornwell** [comment]
@Abanesjo I can see the camera topics now...could I theoretically use a package like [this](https://github.com/mlaiacker/rosbag2video) to extract the frames from the topics below:
                   Topic: /insta_image_yuv | Type: sensor_msgs/msg/Image | Count: 705 | Serialization Format: cdr
                   Topic: /front_camera/image_raw/compressed | Type: sensor_msgs/msg/CompressedImage | Count: 293 | Serialization Format: cdr
                   Topic: /back_camera/image_raw/compressed | Type: sensor_msgs/msg/CompressedImage | Count: 293 | Serialization Format: cdr

**Comment by Eecornwell** [comment]
Answering my own question for others to benefit, just use this script to extract the frames from the topics
```
"""
pip install rosbags
pip install rosbags-image

Insta360 Image Topics:
/front_camera/image_raw/compressed
/back_camera/image_raw/compressed
"""

import os
import cv2
from pathlib import Path
from rosbags.highlevel import AnyReader
from rosbags.image import message_to_cvimage

bag_dir = 'rosbag2_2025_03_04-01_46_57'
topic = '/back_camera/image_raw/compressed'
output_dir = "./output_back"

count = 0
os.makedirs(output_dir, exist_ok=True)
with AnyReader([Path(bag_dir)]) as reader:
    # topic and msgtype information is available on .connections list
    for connection in reader.connections:
        print(connection.topic, connection.msgtype)
    for connection, timestamp, rawdata in reader.messages():
        if connection.topic == topic: # topic Name of images
            msg = reader.deserialize(rawdata, connection.msgtype)
            img = message_to_cvimage(msg, 'bgr8') # change encoding type if needed
            cv2.imwrite(f"{output_dir}/frame%06i.png" % count, img)
            count += 1
```
